version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: iiot_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user_iiot
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: iiot_events_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  influxdb:
    image: influxdb:2.7
    container_name: iiot_influx
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user_iiot
      DOCKER_INFLUXDB_INIT_PASSWORD: securepassword
      DOCKER_INFLUXDB_INIT_ORG: chesta-iiot
      DOCKER_INFLUXDB_INIT_BUCKET: iiot-telemetry
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: pA9rY_xW8LqVnU5mK2tZ1jB7hG4sX0cY3dE6fR9vT8==
    restart: always

  backend:
    build: .
    container_name: iiot_backend_server
    ports:
      - "4000:3000"
      - "4001:3001"
      - "4005:3005"
      - "4006:3006"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - influxdb
      - postgres
    environment:
      POSTGRES_HOST: postgres
      INFLUX_HOST: influxdb
      INFLUX_TOKEN: pA9rY_xW8LqVnU5mK2tZ1jB7hG4sX0cY3dE6fR9vT8==
    restart: always

volumes:
  postgres_data:
  influxdb_data:
